#!/usr/bin/env python3
"""
generate_docs.py — Bithat Secure Vault (BSV) architecture repository generator.

Renders the entire docs/ tree from tools/rfc_registry.py: directory READMEs,
the RFC index and per-RFC scaffolds, cross-references and dependency diagrams,
the full set of architecture indexes, reusable templates, ADRs, cross-cutting
Mermaid diagrams, the architecture review, and the implementation roadmap.

Idempotent. Never touches ROADMAP.md or the migrated part files produced by
split_roadmap.py (it only writes READMEs/references/glossaries for those RFCs).

Usage:  python3 tools/generate_docs.py
"""
from __future__ import annotations

from pathlib import Path

from rfc_registry import (
    REGISTRY, MIGRATED_PARTS, all_rfc_ids, CATEGORIES, STATUS,
)

REPO = Path(__file__).resolve().parents[1]
DOCS = REPO / "docs"

# --- normative helpers -----------------------------------------------------

GEN_NOTE = (
    "<!-- GENERATED by tools/generate_docs.py from tools/rfc_registry.py. "
    "Edit the registry and regenerate; do not hand-edit generated files. -->\n"
)


def mermaid(code: str) -> str:
    return "```mermaid\n" + code.rstrip() + "\n```\n"


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not text.endswith("\n"):
        text += "\n"
    path.write_text(text, encoding="utf-8")


def title_of(rid: str) -> str:
    return REGISTRY[rid]["title"]


def link_rfc(rid: str, from_dir_depth_to_rfcs: str = "..") -> str:
    """Markdown link to an RFC README relative to docs/rfcs/."""
    return f"[{rid} — {title_of(rid)}]({from_dir_depth_to_rfcs}/{rid}/README.md)"


# --- reverse cross-reference derivation ------------------------------------

def derive_relationships():
    """Ensure depends_on/consumed_by and uses/used_by are bidirectional."""
    for rid, r in REGISTRY.items():
        for dep in r["depends_on"]:
            if dep in REGISTRY and rid not in REGISTRY[dep]["consumed_by"]:
                REGISTRY[dep]["consumed_by"].append(rid)
        for u in r["uses"]:
            if u in REGISTRY and rid not in REGISTRY[u]["used_by"]:
                REGISTRY[u]["used_by"].append(rid)
    for rid, r in REGISTRY.items():
        for k in ("depends_on", "consumed_by", "uses", "used_by",
                  "implemented_by"):
            r[k] = sorted(set(x for x in r[k] if x in REGISTRY))


# --- per-RFC rendering -----------------------------------------------------

def render_crossrefs(rid: str) -> str:
    r = REGISTRY[rid]
    lines = ["## Cross-References\n"]

    def block(label, ids):
        if not ids:
            return f"- **{label}:** _none_\n"
        return f"- **{label}:** " + ", ".join(
            f"[{i}](../{i}/README.md)" for i in ids) + "\n"

    lines.append(block("Depends on", r["depends_on"]))
    lines.append(block("Consumed by", r["consumed_by"]))
    lines.append(block("Uses", r["uses"]))
    lines.append(block("Used by", r["used_by"]))
    lines.append(block("Implemented by", r["implemented_by"]))
    return "".join(lines) + "\n"


def render_dependency_diagram(rid: str) -> str:
    r = REGISTRY[rid]
    edges = []
    for dep in r["depends_on"]:
        edges.append(f"  {dep} --> {rid}")
    for c in r["consumed_by"]:
        edges.append(f"  {rid} --> {c}")
    if not edges:
        edges.append(f"  {rid}")
    code = "flowchart LR\n" + "\n".join(sorted(set(edges)))
    return mermaid(code)


def render_existing_readme(rid: str) -> str:
    r = REGISTRY[rid]
    parts = MIGRATED_PARTS.get(rid, [])
    out = [GEN_NOTE, f"# {rid} — {r['title']}\n"]
    out.append(f"| Field | Value |\n|---|---|\n")
    out.append(f"| RFC | {rid} |\n")
    out.append(f"| Category | {r['category']} |\n")
    out.append(f"| Status | {STATUS[r['status']]} |\n")
    out.append(f"| Origin | Migrated verbatim from `ROADMAP.md` |\n")
    out.append(f"| Parts | {len(parts)} |\n\n")
    out.append("## Abstract\n\n" + r["abstract"] + "\n\n")
    out.append("## Parts\n\n")
    for i, pt in enumerate(parts, 1):
        out.append(f"{i}. [Part {i:02d} — {pt}](./part-{i:02d}.md)\n")
    out.append("\n")
    if rid == "RFC-0004":
        out.append(
            "> **Review note:** This RFC is under-developed in the source "
            "(single part). See the "
            "[Architecture Review](../../architecture/ARCHITECTURE-REVIEW.md) "
            "for the expansion backlog (passkey ceremony, recovery flow, "
            "session bootstrap, enterprise SSO).\n\n")
    out.append(render_crossrefs(rid))
    out.append("## Dependency Diagram\n\n")
    out.append(render_dependency_diagram(rid))
    out.append("\n## Supporting Documents\n\n")
    out.append("- [References](./references.md)\n- [Glossary](./glossary.md)\n"
               "- [Diagrams](./diagrams/)\n- [Images](./images/)\n\n")
    out.append("---\n\n> Navigation: [RFC Index](../README.md) · "
               "[Architecture Index](../../architecture/README.md)\n")
    return "".join(out)


def render_new_proposal_body(rid: str) -> str:
    """The normative proposal (part-01.md) for a new RFC."""
    r = REGISTRY[rid]
    out = [
        f"---\nrfc: {rid}\ntitle: {r['title']}\npart: 1\n"
        f"part_title: Design Proposal\nstatus: {STATUS[r['status']]}\n"
        f"classification: Internal\n---\n\n",
        f"# {rid} — {r['title']}\n\n",
        "## Part 1 of 1 — Design Proposal\n\n",
        "> Navigation: [RFC Home](./README.md) · [RFC Index](../README.md) · "
        "[Architecture Index](../../architecture/README.md)\n\n---\n\n",
        "# 1. Abstract\n\n" + r["abstract"] + "\n\n",
        "# 2. Status & Motivation\n\n"
        f"This RFC was introduced during the architecture consolidation of "
        f"the BSV platform. It formalizes capabilities that were previously "
        f"referenced by other RFCs but never specified. See the "
        f"[Architecture Review](../../architecture/ARCHITECTURE-REVIEW.md).\n\n",
    ]
    sec = 3
    if r["goals"]:
        out.append(f"# {sec}. Goals\n\n")
        for g in r["goals"]:
            out.append(f"- {g}\n")
        out.append("\n")
        sec += 1
    for title, paras in r["sections"]:
        out.append(f"# {sec}. {title}\n\n")
        for p in paras:
            out.append(p + "\n\n")
        sec += 1
    if r["requirements"]:
        out.append(f"# {sec}. Requirements\n\n")
        for req in r["requirements"]:
            out.append(f"- {req}\n")
        out.append("\n")
        sec += 1
    if r["diagrams"]:
        out.append(f"# {sec}. Diagrams\n\n")
        for d in r["diagrams"]:
            out.append(f"### {d['title']}\n\n")
            out.append(mermaid(d["mermaid"]) + "\n")
        sec += 1
    out.append(f"# {sec}. Cross-References\n\n")
    out.append(render_crossrefs(rid))
    out.append(f"# {sec + 1}. Open Questions & Future Work\n\n")
    out.append("- Refine acceptance criteria with the implementation team.\n")
    out.append("- Add sequence-level detail as dependent RFCs stabilize.\n\n")
    out.append("---\n\n> End of " + rid + " Part 1\n")
    return "".join(out)


def render_new_readme(rid: str) -> str:
    r = REGISTRY[rid]
    out = [GEN_NOTE, f"# {rid} — {r['title']}\n"]
    out.append("| Field | Value |\n|---|---|\n")
    out.append(f"| RFC | {rid} |\n")
    out.append(f"| Category | {r['category']} |\n")
    out.append(f"| Status | {STATUS[r['status']]} |\n")
    out.append(f"| Origin | New proposal (architecture consolidation) |\n")
    out.append(f"| Parts | 1 |\n\n")
    out.append("## Abstract\n\n" + r["abstract"] + "\n\n")
    if r["goals"]:
        out.append("## Goals\n\n")
        for g in r["goals"]:
            out.append(f"- {g}\n")
        out.append("\n")
    out.append("## Parts\n\n1. [Part 01 — Design Proposal](./part-01.md)\n\n")
    out.append(render_crossrefs(rid))
    out.append("## Dependency Diagram\n\n")
    out.append(render_dependency_diagram(rid))
    out.append("\n## Supporting Documents\n\n")
    out.append("- [References](./references.md)\n- [Glossary](./glossary.md)\n"
               "- [Diagrams](./diagrams/)\n- [Images](./images/)\n\n")
    out.append("---\n\n> Navigation: [RFC Index](../README.md) · "
               "[Architecture Index](../../architecture/README.md)\n")
    return "".join(out)


def render_references(rid: str) -> str:
    return (GEN_NOTE + f"# {rid} — References\n\n"
            "Normative and informative references for this RFC.\n\n"
            "## Normative\n\n"
            "- RFC 9106 — Argon2 Memory-Hard Function\n"
            "- RFC 5869 — HKDF\n"
            "- RFC 5116 — Authenticated Encryption (AEAD)\n"
            "- NIST SP 800-38D — AES-GCM\n"
            "- NIST SP 800-63B — Digital Identity Guidelines\n\n"
            "## Informative\n\n"
            "- Apple Platform Security Guide\n"
            "- OWASP ASVS v4 / OWASP MASVS\n"
            "- FIDO2 / WebAuthn Level 3\n\n"
            "## Related RFCs\n\n"
            + "".join(f"- [{i}](../{i}/README.md)\n"
                      for i in sorted(set(REGISTRY[rid]["depends_on"] +
                                          REGISTRY[rid]["consumed_by"])))
            + ("- _none_\n" if not (REGISTRY[rid]["depends_on"] or
                                    REGISTRY[rid]["consumed_by"]) else ""))


def render_glossary(rid: str) -> str:
    r = REGISTRY[rid]
    out = [GEN_NOTE, f"# {rid} — Glossary\n\n"]
    if r["glossary"]:
        out.append("| Term | Definition |\n|---|---|\n")
        for term, d in r["glossary"]:
            out.append(f"| {term} | {d} |\n")
    else:
        out.append("See the [master glossary](../../glossary/README.md).\n")
    out.append("\nSee also the [master glossary](../../glossary/README.md).\n")
    return "".join(out)


def render_rfc_diagram_file(rid: str, d: dict) -> str:
    return (GEN_NOTE + f"# {rid} — {d['title']}\n\n" + mermaid(d["mermaid"]) +
            f"\n> Part of [{rid}](../README.md).\n")


# --- indexes ---------------------------------------------------------------

def render_rfc_index() -> str:
    out = [GEN_NOTE, "# RFC Index\n\n",
           "Authoritative index of every Request for Comments (RFC) in the "
           "Bithat Secure Vault architecture. RFC numbering is canonical and "
           "governed by [RFC-0029 Architecture Governance](./RFC-0029/README.md).\n\n"]
    out.append("| RFC | Title | Category | Status | Origin |\n")
    out.append("|---|---|---|---|---|\n")
    for rid in all_rfc_ids():
        r = REGISTRY[rid]
        origin = "Migrated" if r["existing"] else "New proposal"
        out.append(f"| [{rid}](./{rid}/README.md) | {r['title']} | "
                   f"{r['category']} | {STATUS[r['status']]} | {origin} |\n")
    out.append("\n## By Category\n\n")
    for cat in CATEGORIES:
        ids = [i for i in all_rfc_ids() if REGISTRY[i]["category"] == cat]
        if ids:
            out.append(f"- **{cat}:** " +
                       ", ".join(f"[{i}](./{i}/README.md)" for i in ids) + "\n")
    out.append("\n> Navigation: [Architecture Index](../architecture/README.md)"
               " · [Docs Home](../README.md)\n")
    return "".join(out)


def render_dependency_graph() -> str:
    out = [GEN_NOTE, "# RFC Dependency Graph\n\n",
           "Global dependency graph across all RFCs. An arrow `A --> B` means "
           "*B depends on A* (A is consumed by B).\n\n"]
    edges = []
    for rid in all_rfc_ids():
        for dep in REGISTRY[rid]["depends_on"]:
            edges.append(f"  {dep} --> {rid}")
    code = "flowchart LR\n" + "\n".join(sorted(set(edges)))
    out.append(mermaid(code))
    out.append("\n> Navigation: [Architecture Index](./README.md)\n")
    return "".join(out)


def render_component_index() -> str:
    out = [GEN_NOTE, "# Component Index\n\n",
           "Every named architectural component and its owning RFC.\n\n",
           "| Component | Owning RFC | Category |\n|---|---|---|\n"]
    rows = []
    for rid in all_rfc_ids():
        for c in REGISTRY[rid]["components"]:
            rows.append((c, rid, REGISTRY[rid]["category"]))
    for c, rid, cat in sorted(rows):
        out.append(f"| {c} | [{rid}](../rfcs/{rid}/README.md) | {cat} |\n")
    out.append("\n> Navigation: [Architecture Index](./README.md)\n")
    return "".join(out)


def render_architecture_index() -> str:
    out = [GEN_NOTE, "# Architecture Index\n\n",
           "The master hub for the Bithat Secure Vault (BSV) architecture "
           "repository. Every architecture artifact is discoverable from here.\n\n"]
    out.append("## Indexes\n\n"
               "- [RFC Index](../rfcs/README.md)\n"
               "- [Component Index](./component-index.md)\n"
               "- [Security Index](./security-index.md)\n"
               "- [Threat Index](./threat-index.md)\n"
               "- [Storage Index](./storage-index.md)\n"
               "- [Diagram Index](../diagrams/README.md)\n"
               "- [Decision Index](../decisions/README.md)\n"
               "- [API Index](../api/README.md)\n"
               "- [Testing Index](../testing/README.md)\n"
               "- [Glossary](../glossary/README.md)\n\n")
    out.append("## Planning\n\n"
               "- [Architecture Review](./ARCHITECTURE-REVIEW.md)\n"
               "- [Implementation Roadmap](./implementation-roadmap.md)\n"
               "- [RFC Dependency Graph](./dependency-graph.md)\n\n")
    out.append("## Layered View\n\n")
    out.append(mermaid(
        "flowchart TB\n"
        "  subgraph Experience\n    UI[RFC-0016 UI]\n    CB[RFC-0014 Clipboard/UI]\n  end\n"
        "  subgraph Runtime\n    RT[RFC-0008 Runtime/Session]\n    MON[RFC-0022 Monitor]\n    RISK[RFC-0023 Risk]\n  end\n"
        "  subgraph Identity\n    AUTH[RFC-0004 Auth]\n    SE[RFC-0006 Secure Enclave]\n    DEV[RFC-0024 Device Trust]\n  end\n"
        "  subgraph Cryptography\n    CRY[RFC-0003 Crypto]\n    KM[RFC-0007 Key Mgmt]\n    MEM[RFC-0009 Memory]\n    MIG[RFC-0013 Migration]\n  end\n"
        "  subgraph Storage\n    ST[RFC-0005 Storage]\n    OM[RFC-0025 Object Model]\n    SP[RFC-0019 Provider SDK]\n  end\n"
        "  subgraph DataProtection\n    BK[RFC-0010 Backup]\n    RC[RFC-0011 Recovery]\n    AUD[RFC-0012 Audit]\n  end\n"
        "  subgraph Enterprise\n    POL[RFC-0015 Policy]\n    EN[RFC-0018 Enterprise]\n    SY[RFC-0017 Sync]\n  end\n"
        "  Experience --> Runtime --> Identity --> Cryptography --> Storage\n"
        "  Cryptography --> DataProtection\n  Enterprise --> DataProtection\n"))
    out.append("\n> Navigation: [Docs Home](../README.md)\n")
    return "".join(out)


def render_security_index() -> str:
    sec_rfcs = [i for i in all_rfc_ids()
                if REGISTRY[i]["category"] in ("Security", "Cryptography",
                                               "Data Protection")]
    out = [GEN_NOTE, "# Security Index\n\n",
           "Security-relevant RFCs, controls, and requirement families.\n\n",
           "## Security & Crypto RFCs\n\n"]
    for i in sec_rfcs:
        out.append(f"- [{i} — {REGISTRY[i]['title']}](../rfcs/{i}/README.md)\n")
    out.append("\n## Requirement Families\n\n"
               "| Prefix | Domain | Source |\n|---|---|---|\n"
               "| SR-* | Security Requirements | RFC-0002 |\n"
               "| SO-* | Security Objectives | RFC-0002 |\n"
               "| INV-* | Cryptographic Invariants | RFC-0003 |\n"
               "| CP-* | Cryptographic Protocols | RFC-0003 |\n"
               "| SE-REQ-* | Secure Enclave | RFC-0006 |\n"
               "| KM-REQ-* | Key Management | RFC-0007 |\n"
               "| MEM-REQ-* | Secure Memory | RFC-0009 |\n"
               "| AU-REQ-* | Audit | RFC-0012 |\n\n")
    out.append("> Navigation: [Architecture Index](./README.md)\n")
    return "".join(out)


def render_threat_index() -> str:
    return (GEN_NOTE + "# Threat Index\n\n"
            "Consolidated pointer to the threat model. Threat identifiers are "
            "defined in [RFC-0002](../rfcs/RFC-0002/README.md).\n\n"
            "| Family | Meaning | Source |\n|---|---|---|\n"
            "| TA-* | Threat Actors | RFC-0002 Part 1 |\n"
            "| TM-* | STRIDE Threats | RFC-0002 Part 3 |\n"
            "| TR-* | Runtime Threats | RFC-0003 Part 9 / RFC-0022 |\n"
            "| RR-* | Risk Register | RFC-0002 Part 7 |\n"
            "| AC-* | Abuse Cases | RFC-0002 Part 4 |\n\n"
            "## Threat Flow (representative)\n\n"
            + mermaid("flowchart LR\n"
                      "  M[Malware] --> U[User Unlocks]\n"
                      "  U --> Mem[Plaintext in Memory]\n"
                      "  U --> CB[Clipboard]\n"
                      "  Mem --> X[Exfiltration]\n"
                      "  CB --> X")
            + "\n> Navigation: [Architecture Index](./README.md)\n")


def render_storage_index() -> str:
    st = [i for i in all_rfc_ids() if REGISTRY[i]["category"] == "Storage"]
    out = [GEN_NOTE, "# Storage Index\n\n", "Storage-related RFCs and engines.\n\n"]
    for i in st:
        out.append(f"- [{i} — {REGISTRY[i]['title']}](../rfcs/{i}/README.md)\n")
    out.append("\n## Storage Engines (RFC-0005)\n\n"
               "- Transaction Manager · Object Engine · Attachment Engine · "
               "Index Engine · OSAL\n\n"
               "> Navigation: [Architecture Index](./README.md)\n")
    return "".join(out)


def render_diagram_index() -> str:
    out = [GEN_NOTE, "# Diagram Index\n\n",
           "All Mermaid diagrams in the repository. Cross-cutting diagrams are "
           "in this directory; RFC-specific diagrams live under each RFC's "
           "`diagrams/` folder.\n\n"]
    out.append("## Cross-Cutting Diagrams\n\n")
    for name, title in CROSS_DIAGRAMS_LIST:
        out.append(f"- [{title}](./{name}.md)\n")
    out.append("\n## RFC Diagrams\n\n")
    for rid in all_rfc_ids():
        ds = REGISTRY[rid]["diagrams"]
        if ds:
            out.append(f"- **{rid}**: " + ", ".join(
                f"[{d['title']}](../rfcs/{rid}/diagrams/{d['name']}.md)"
                for d in ds) + "\n")
    out.append("\n> Navigation: [Architecture Index](../architecture/README.md)\n")
    return "".join(out)


def render_glossary_master() -> str:
    terms = {}
    for rid in all_rfc_ids():
        for term, d in REGISTRY[rid]["glossary"]:
            terms.setdefault(term, (d, rid))
    # curated core terms
    core = {
        "BSV": ("Bithat Secure Vault, the offline-first infrastructure asset vault.", "RFC-0001"),
        "Vault": ("The encrypted repository of objects.", "RFC-0005"),
        "Object": ("The uniform unit of storage.", "RFC-0025"),
        "AEAD": ("Authenticated Encryption with Associated Data.", "RFC-0003"),
        "Argon2id": ("Memory-hard password-based key derivation function.", "RFC-0003"),
        "AES-256-GCM": ("Authenticated symmetric cipher used by BSV.", "RFC-0003"),
    }
    terms = {**core, **terms}
    out = [GEN_NOTE, "# Master Glossary\n\n",
           "Canonical terminology for the BSV architecture. Per-RFC glossaries "
           "link back here.\n\n", "| Term | Definition | Source |\n|---|---|---|\n"]
    for term in sorted(terms, key=str.lower):
        d, rid = terms[term]
        out.append(f"| {term} | {d} | [{rid}](../rfcs/{rid}/README.md) |\n")
    out.append("\n> Navigation: [Architecture Index](../architecture/README.md)\n")
    return "".join(out)


# --- ADRs ------------------------------------------------------------------

ADRS = [
    ("Offline First", "The vault MUST function fully offline; cloud connectivity MUST NOT be required to unlock or use the vault."),
    ("Native macOS Application (SwiftUI)", "The application SHALL be a native macOS SwiftUI app to access Secure Enclave, Keychain, CryptoKit, and platform security directly."),
    ("Passkey First", "Passkeys SHALL be the preferred authentication method for phishing resistance and hardware backing."),
    ("No Master Password", "A master password SHALL NOT be the primary authenticator; authentication uses Touch ID, Passkey, then recovery."),
    ("Secure Enclave", "The wrapped Vault Root Key SHALL be protected by the Secure Enclave; the Enclave authorizes but never decrypts vault data."),
    ("Separate Attachment Encryption", "Every attachment SHALL receive an independent DEK to reduce blast radius and enable rotation."),
    ("No Browser Extension (v1)", "No browser extension SHALL ship in v1 to minimize attack surface."),
    ("No Telemetry", "Telemetry SHALL be disabled by default to protect privacy and metadata."),
    ("Zero Plaintext Persistence", "Plaintext SHALL NEVER reach persistent storage under any condition."),
    ("Zero Proprietary Cryptography", "Only standardized, publicly reviewed algorithms SHALL be used."),
    ("Memory Is Hostile", "RAM SHALL be treated as compromised; plaintext lifetime SHALL be minimized and buffers zeroized."),
    ("Clipboard Is Hostile", "Clipboard contents SHALL auto-expire and be overwritten before clearing."),
    ("Immutable Audit", "Audit records SHALL be append-only and immutable."),
    ("One Vault Key", "Each vault SHALL have exactly one Vault Root Key to simplify recovery and backup."),
    ("Independent DEKs", "Each encrypted object SHALL receive its own DEK for cryptographic isolation."),
    ("SQLCipher Storage", "SQLite + SQLCipher SHALL be the initial storage backend behind the OSAL."),
    ("App Sandbox", "The App Sandbox SHALL always be enabled to limit filesystem access."),
    ("Hardened Runtime", "The Hardened Runtime SHALL be mandatory to resist runtime injection."),
    ("Signed Releases", "Every release SHALL be code-signed and notarized; no exceptions."),
    ("Recovery Package", "A recovery package SHALL be generated once, kept outside the vault, for disaster recovery."),
]


def render_adr(num: int, title: str, decision: str) -> str:
    return (GEN_NOTE + f"# ADR-{num:04d} — {title}\n\n"
            "| Field | Value |\n|---|---|\n"
            f"| Status | Accepted |\n"
            f"| Origin | RFC-0002 Part 9 (SAD-{num:04d}) |\n\n"
            "## Context\n\n"
            "This decision was ratified as a Security Architecture Decision "
            "(SAD) in the threat model and is binding across the platform.\n\n"
            "## Decision\n\n" + decision + "\n\n"
            "## Consequences\n\n"
            "Changing this decision requires a superseding RFC per "
            "[RFC-0029 Architecture Governance](../rfcs/RFC-0029/README.md).\n\n"
            "## References\n\n"
            "- [RFC-0002 Part 9 — Security Architecture Decisions]"
            "(../rfcs/RFC-0002/part-09.md)\n\n"
            "> Navigation: [Decision Index](./README.md)\n")


def render_decision_index() -> str:
    out = [GEN_NOTE, "# Decision Index\n\n",
           "Architecture Decision Records (ADRs). ADR-0001..0020 are the "
           "ratified Security Architecture Decisions (SAD) from "
           "[RFC-0002 Part 9](../rfcs/RFC-0002/part-09.md).\n\n",
           "| ADR | Title | Status |\n|---|---|---|\n"]
    for i, (t, _d) in enumerate(ADRS, 1):
        out.append(f"| [ADR-{i:04d}](../adr/ADR-{i:04d}.md) | {t} | Accepted |\n")
    out.append("\n> Navigation: [Architecture Index](../architecture/README.md)\n")
    return "".join(out)


# --- cross-cutting diagrams -------------------------------------------------

CROSS_DIAGRAMS = [
    ("system-context", "System Context",
     "flowchart LR\n  U[User] --> BIO[Touch ID / Passkey]\n  BIO --> APP[BSV App]\n"
     "  APP --> CE[Crypto Engine]\n  CE --> KC[Keychain]\n  KC --> SE[Secure Enclave]\n"
     "  CE --> DB[(Encrypted Vault)]\n  CE --> FS[Encrypted Attachments]\n  DB --> BK[Offline Backup]"),
    ("trust-boundaries", "Trust Boundaries",
     "flowchart TB\n  subgraph Untrusted\n    NET[Internet]\n    CLIP[Clipboard]\n    FND[Finder]\n  end\n"
     "  subgraph Trusted\n    CE[Crypto Engine]\n    DB[(Vault DB)]\n    MEM[Secure Memory]\n  end\n"
     "  subgraph Hardware\n    SE[Secure Enclave]\n  end\n  Untrusted -. hostile .-> Trusted\n  Trusted --> Hardware"),
    ("vault-state-machine", "Vault State Machine",
     "stateDiagram-v2\n  [*] --> Uninitialized\n  Uninitialized --> Creating\n  Creating --> Locked\n"
     "  Locked --> Authenticating\n  Authenticating --> Unlocked\n  Authenticating --> Locked\n"
     "  Unlocked --> Locking\n  Locking --> Locked\n  Locked --> Migrating\n  Migrating --> Locked\n"
     "  Locked --> Recovering\n  Recovering --> Locked\n  Locked --> Destroyed\n  Destroyed --> [*]"),
    ("unlock-sequence", "Unlock Sequence",
     "sequenceDiagram\n  participant U as User\n  participant T as Touch ID\n  participant SE as Secure Enclave\n"
     "  participant C as Crypto\n  participant V as Vault\n  U->>T: Authenticate\n  T->>SE: Authorization\n"
     "  SE-->>C: Release Wrapped Key\n  C->>V: Decrypt Metadata\n  V-->>C: Encrypted Blocks\n  C-->>U: Plaintext Objects"),
    ("storage-layout", "Storage Layout",
     "flowchart TB\n  H[File Header] --> M[Vault Metadata]\n  M --> IDX[Object Index]\n  IDX --> S[Secret Records]\n"
     "  S --> AM[Attachment Manifest]\n  AM --> CH[Attachment Chunks]\n  CH --> AU[Audit Metadata]\n  AU --> F[Integrity Footer]"),
    ("deployment", "Deployment (v1 macOS)",
     "flowchart TB\n  subgraph mac [User Mac]\n    APP[BSV.app]\n    KC[Keychain]\n    SE[Secure Enclave]\n    FV[FileVault Disk]\n  end\n"
     "  APP --> KC --> SE\n  APP --> FV\n  APP -. optional TLS .-> UP[Update / License]"),
    ("auth-flow", "Authentication Flow",
     "stateDiagram-v2\n  [*] --> Unauthenticated\n  Unauthenticated --> Authenticating\n"
     "  Authenticating --> Authorized\n  Authorized --> SessionActive\n  SessionActive --> Expired\n  Expired --> Locked\n  Locked --> [*]"),
    ("recovery-flow", "Recovery Flow",
     "flowchart LR\n  A[Authenticate Recovery] --> B[Validate Recovery Key]\n  B --> C[New Device Binding]\n"
     "  C --> D[New Wrapped Root Key]\n  D --> E[Invalidate Prior Session]\n  E --> F[Complete]"),
    ("sync-flow", "Synchronization Flow (v2)",
     "sequenceDiagram\n  participant A as Device A\n  participant S as Sync Server (untrusted)\n  participant B as Device B\n"
     "  A->>S: Push ciphertext versions\n  B->>S: Pull ciphertext versions\n  B->>B: Resolve conflicts locally"),
]
CROSS_DIAGRAMS_LIST = [(n, t) for (n, t, _c) in CROSS_DIAGRAMS]


def render_cross_diagram(name: str, title: str, code: str) -> str:
    return (GEN_NOTE + f"# {title}\n\n" + mermaid(code) +
            "\n> Navigation: [Diagram Index](./README.md)\n")


# --- templates -------------------------------------------------------------

TEMPLATES = {
    "rfc-template.md":
        "# RFC-XXXX — <Title>\n\n"
        "| Field | Value |\n|---|---|\n| RFC | RFC-XXXX |\n"
        "| Category | <Foundation/Security/...> |\n| Status | Proposed |\n"
        "| Parts | 1 |\n\n## Abstract\n\n<one paragraph>\n\n"
        "## Goals\n\n- <goal>\n\n## Cross-References\n\n"
        "- **Depends on:** <RFC-XXXX>\n- **Consumed by:** <RFC-XXXX>\n\n"
        "## Parts\n\n1. Part 01 — Design Proposal (`part-01.md`)\n",
    "part-template.md":
        "---\nrfc: RFC-XXXX\ntitle: <Title>\npart: N\npart_title: <Part Title>\n"
        "status: Draft\nclassification: Internal\n---\n\n"
        "# RFC-XXXX — <Title>\n\n## Part N of M — <Part Title>\n\n"
        "> Navigation: [RFC Home](./README.md) · [RFC Index](../README.md)\n\n---\n\n"
        "# 1. Purpose\n\n<...>\n\n# 2. <Section>\n\n<...>\n",
    "adr-template.md":
        "# ADR-XXXX — <Title>\n\n| Field | Value |\n|---|---|\n"
        "| Status | Proposed |\n\n## Context\n\n<...>\n\n## Decision\n\n"
        "We SHALL <...>\n\n## Consequences\n\n<...>\n",
    "diagram-template.md":
        "# <Diagram Title>\n\n```mermaid\nflowchart LR\n  A --> B\n```\n",
    "glossary-template.md":
        "# RFC-XXXX — Glossary\n\n| Term | Definition |\n|---|---|\n"
        "| <Term> | <Definition> |\n",
    "references-template.md":
        "# RFC-XXXX — References\n\n## Normative\n\n- <...>\n\n"
        "## Informative\n\n- <...>\n\n## Related RFCs\n\n- <RFC-XXXX>\n",
}


# --- directory READMEs -----------------------------------------------------

DIR_READMES = {
    "api": ("API Index",
            "API contracts for the Vault API surface. API definitions are "
            "derived from the [Object Model (RFC-0025)](../rfcs/RFC-0025/README.md) "
            "and consumed by the [Developer SDK (RFC-0021)](../rfcs/RFC-0021/README.md).\n\n"
            "## Surfaces\n\n- Vault lifecycle (create/open/lock/unlock)\n"
            "- Object CRUD & versioning\n- Attachment streaming\n- Search\n"
            "- Backup / restore / recovery\n"),
    "sdk": ("SDK",
            "Developer SDK documentation. Specified by "
            "[RFC-0021 Developer SDK & Code Generation](../rfcs/RFC-0021/README.md).\n\n"
            "SDK bindings are generated from the object model and API "
            "definitions to prevent drift.\n"),
    "compliance": ("Compliance",
                   "Compliance mappings and control coverage. Targets: SOC 2, "
                   "ISO 27001, OWASP ASVS, NIST SP 800-63B, CIS Controls, "
                   "Apple Platform Security.\n\n"
                   "See the [Security Index](../architecture/security-index.md) "
                   "and [RFC-0002](../rfcs/RFC-0002/README.md).\n"),
    "testing": ("Testing Index",
                "Testing and verification strategy. Specified by "
                "[RFC-0026 Testing & Verification Specification](../rfcs/RFC-0026/README.md).\n\n"
                "## Levels\n\n- Unit · Integration · Property · Fuzz · "
                "Crash-injection · Penetration · Known-Answer Tests (KAT)\n\n"
                "Every security requirement (SR-*) maps to a verification method.\n"),
    "deployment": ("Deployment",
                   "Build, signing, notarization, SBOM, reproducible builds, "
                   "and release channels. Specified by "
                   "[RFC-0027 Deployment & Release Engineering](../rfcs/RFC-0027/README.md).\n"),
    "operations": ("Operations",
                   "Operational runbooks and incident response. Specified by "
                   "[RFC-0028 Incident Response & Operations](../rfcs/RFC-0028/README.md).\n"),
    "images": ("Images",
               "Binary image assets referenced by documentation. Prefer "
               "Mermaid diagrams (text) over raster images wherever possible.\n"),
}


# --- top-level docs README + review + roadmap ------------------------------

def render_docs_home() -> str:
    return (GEN_NOTE + "# Bithat Secure Vault — Architecture Repository\n\n"
            "This repository is the **official architecture documentation** "
            "for the Bithat Secure Vault (BSV): an offline-first, secure-by-"
            "default infrastructure asset vault for macOS.\n\n"
            "> The historical origin document is preserved at "
            "[`ROADMAP.md`](../ROADMAP.md). All architecture is now organized "
            "into versioned, cross-referenced RFCs, ADRs, diagrams, and "
            "indexes generated from a single registry "
            "(`tools/rfc_registry.py`).\n\n"
            "## Start Here\n\n"
            "- [Architecture Index](./architecture/README.md) — master hub\n"
            "- [RFC Index](./rfcs/README.md) — all RFCs\n"
            "- [Architecture Review](./architecture/ARCHITECTURE-REVIEW.md) — "
            "gap analysis of the source material\n"
            "- [Implementation Roadmap](./architecture/implementation-roadmap.md)\n"
            "- [Decision Index (ADRs)](./decisions/README.md)\n"
            "- [Glossary](./glossary/README.md)\n\n"
            "## Repository Layout\n\n"
            "```text\n"
            "docs/\n"
            "  architecture/   indexes, review, roadmap, dependency graph\n"
            "  rfcs/           RFC-0001 .. RFC-0029 (each with parts + diagrams)\n"
            "  diagrams/       cross-cutting Mermaid diagrams\n"
            "  adr/            architecture decision records\n"
            "  decisions/      decision index\n"
            "  api/  sdk/      interface & SDK docs\n"
            "  glossary/       master glossary\n"
            "  compliance/     compliance mappings\n"
            "  testing/        verification strategy\n"
            "  deployment/     release engineering\n"
            "  operations/     runbooks & incident response\n"
            "  templates/      reusable RFC/ADR/diagram templates\n"
            "  images/         binary assets\n"
            "tools/            registry + generators\n"
            "```\n\n"
            "## Regenerating\n\n"
            "```bash\n"
            "python3 tools/split_roadmap.py      # migrate RFC-0001..0005 parts\n"
            "python3 tools/generate_docs.py      # render indexes, scaffolds, ADRs\n"
            "```\n\n"
            f"## At a Glance\n\n- **RFCs:** {len(all_rfc_ids())} "
            f"({sum(1 for i in all_rfc_ids() if REGISTRY[i]['existing'])} "
            f"migrated, {sum(1 for i in all_rfc_ids() if not REGISTRY[i]['existing'])} "
            "new proposals)\n"
            "- **ADRs:** 20 ratified security architecture decisions\n"
            "- **Diagrams:** cross-cutting + per-RFC Mermaid\n")


def render_review() -> str:
    return (GEN_NOTE + "# Architecture Review (Enterprise Review)\n\n"
            "This review records issues identified in the source material "
            "(`ROADMAP.md`) during the consolidation into this repository. "
            "Per the review mandate, issues are **documented, not silently "
            "fixed**; each is tracked to a resolution (new RFC, normalization, "
            "or backlog item).\n\n"
            "## 1. Summary\n\n"
            "The source contained five well-developed RFCs (RFC-0001..0005) "
            "plus numerous forward references to RFCs that were never written. "
            "The material was internally strong but suffered from inconsistent "
            "RFC numbering, an under-developed authentication RFC, and missing "
            "specifications for whole subsystems.\n\n"
            "## 2. Inconsistencies\n\n"
            "| ID | Issue | Resolution |\n|---|---|---|\n"
            "| RV-01 | Forward references reuse the same RFC number for "
            "different subsystems (e.g. RFC-0006 appears as \"Secure Enclave\", "
            "\"Storage Engine\", \"Key Management\", \"Runtime\", \"Database\"). | "
            "Canonical numbering fixed in `rfc_registry.py`; see [RFC Index](../rfcs/README.md). |\n"
            "| RV-02 | Inconsistent frontmatter keys/casing (`rfc:` vs `RFC:`, "
            "`title:` vs `Title:`). | Normalized during migration. |\n"
            "| RV-03 | Per-part section numbering restarts arbitrarily. | "
            "Preserved verbatim in migrated parts; new RFCs use consistent numbering. |\n"
            "| RV-04 | Mixed heading levels for RFC/Part titles. | Standardized nav headers added. |\n\n"
            "## 3. Duplicated Concepts\n\n"
            "| ID | Duplication | Resolution |\n|---|---|---|\n"
            "| RV-05 | Secure Enclave specified in RFC-0003 Part 8 and referenced as a separate RFC. | Promoted to [RFC-0006](../rfcs/RFC-0006/README.md). |\n"
            "| RV-06 | Key management in RFC-0003 Part 2 and referenced as RFC-0007/0008. | Consolidated in [RFC-0007](../rfcs/RFC-0007/README.md). |\n"
            "| RV-07 | Secure memory in RFC-0003 Part 7 and referenced separately. | Promoted to [RFC-0009](../rfcs/RFC-0009/README.md). |\n"
            "| RV-08 | Migration in RFC-0003 Part 10 and RFC-0005. | Consolidated in [RFC-0013](../rfcs/RFC-0013/README.md). |\n\n"
            "## 4. Under-Developed RFCs\n\n"
            "| ID | Issue | Resolution |\n|---|---|---|\n"
            "| RV-09 | RFC-0004 Authentication has only Part 1 (philosophy). Missing: passkey ceremony, recovery flow, session bootstrap, enterprise SSO, state-machine detail. | Backlog: expand RFC-0004 Parts 2–5; dependencies now formalized via RFC-0006/0008/0011/0018. |\n\n"
            "## 5. Missing Specifications (now created)\n\n"
            "The following subsystems were referenced but unspecified and are "
            "now created as proposals: "
            + ", ".join(f"[{i}](../rfcs/{i}/README.md)"
                        for i in all_rfc_ids() if not REGISTRY[i]["existing"])
            + ".\n\n"
            "## 6. Missing Cross-Cutting Artifacts (now created)\n\n"
            "- Threat/state/deployment/recovery/sync diagrams — see [Diagram Index](../diagrams/README.md).\n"
            "- Testing strategy — [RFC-0026](../rfcs/RFC-0026/README.md).\n"
            "- Deployment strategy — [RFC-0027](../rfcs/RFC-0027/README.md).\n"
            "- Governance — [RFC-0029](../rfcs/RFC-0029/README.md).\n"
            "- ADRs extracted from SAD — [Decision Index](../decisions/README.md).\n\n"
            "## 7. Residual Risks / Open Items\n\n"
            "- Post-quantum migration path is reserved but not committed (RFC-0003 Part 10 / RFC-0013).\n"
            "- Malware-while-unlocked remains an accepted residual risk (RFC-0002 Part 7).\n"
            "- Multi-device sync (RFC-0017) and enterprise (RFC-0018) are v2/v3 scope.\n\n"
            "> Navigation: [Architecture Index](./README.md)\n")


PHASES = [
    ("Architecture", "RFC-0001, RFC-0002",
     "Approved RFC set, threat model, ADRs",
     "None",
     "Ratified architecture repository",
     "Ambiguity in scope; scope creep",
     "All P0 RFCs Accepted; review sign-off"),
    ("Foundation", "Architecture phase outputs",
     "Runtime skeleton, module boundaries (RFC-0008), OSAL contract (RFC-0005/0019)",
     "RFC-0005, RFC-0008, RFC-0019",
     "Storage provider contract + session lifecycle",
     "Wrong abstractions ossifying early",
     "OSAL certification suite defined; session state machine implemented"),
    ("Crypto", "Foundation",
     "Crypto Engine, key hierarchy, profiles (RFC-0003, RFC-0007)",
     "RFC-0003, RFC-0006, RFC-0007, RFC-0009",
     "Working encryption, key mgmt, secure memory",
     "Nonce reuse; weak RNG; memory leakage",
     "KAT suite passing; zeroization verified; no plaintext persistence"),
    ("Storage", "Crypto",
     "Object/attachment/index engines, transactions (RFC-0005, RFC-0025)",
     "RFC-0003, RFC-0005, RFC-0013, RFC-0025",
     "Crash-safe encrypted object store",
     "Corruption; migration failure",
     "Crash-injection tests pass; migration rollback verified"),
    ("Authentication", "Crypto, Storage",
     "Auth service, Secure Enclave integration (RFC-0004, RFC-0006)",
     "RFC-0004, RFC-0006, RFC-0011",
     "Passkey/Touch ID unlock + recovery",
     "Auth bypass; recovery abuse",
     "Unlock < 300 ms; recovery drill passes"),
    ("Runtime", "Authentication",
     "Session manager, lock controller, monitor, risk (RFC-0008/0022/0023)",
     "RFC-0008, RFC-0022, RFC-0023",
     "Fail-secure runtime with monitoring",
     "Missed lock events; false positives",
     "All lock triggers verified; risk responses tested"),
    ("UI", "Runtime",
     "SwiftUI shell, secure views, clipboard (RFC-0016, RFC-0014)",
     "RFC-0014, RFC-0016",
     "Usable secure UI",
     "On-screen/clipboard leakage",
     "Clipboard auto-clear verified; no plaintext in view state after lock"),
    ("Data Protection", "Storage, Runtime",
     "Backup/restore, audit engine (RFC-0010, RFC-0011, RFC-0012)",
     "RFC-0010, RFC-0011, RFC-0012",
     "Encrypted backups + immutable audit",
     "Backup tampering; audit gaps",
     "Backup/restore round-trip verified; audit chain validated"),
    ("Enterprise", "Data Protection",
     "Policy, RBAC, approval, SSO (RFC-0015, RFC-0018)",
     "RFC-0015, RFC-0018",
     "Enterprise controls",
     "Privilege escalation; policy bypass",
     "RBAC least-privilege verified; policy enforcement audited"),
    ("SDK", "Storage, Enterprise",
     "Developer SDK + codegen (RFC-0021), Object Model (RFC-0025)",
     "RFC-0019, RFC-0021, RFC-0025",
     "Stable, generated SDK",
     "API drift; compatibility breaks",
     "Generated bindings pass conformance; versioning policy in place"),
    ("Plugins", "SDK, Runtime",
     "Sandboxed plugin host (RFC-0020)",
     "RFC-0020, RFC-0021",
     "Capability-scoped plugin system",
     "Sandbox escape; secret leakage",
     "Plugins signed & sandboxed; no unauthorized secret access"),
    ("Sync", "Enterprise, Storage",
     "E2E sync + device trust (RFC-0017, RFC-0024)",
     "RFC-0017, RFC-0024",
     "Optional multi-device sync",
     "Server trust; conflict corruption",
     "Server sees only ciphertext; deterministic conflict resolution"),
    ("Release", "All prior phases",
     "Signing, notarization, SBOM, IR (RFC-0027, RFC-0028)",
     "RFC-0026, RFC-0027, RFC-0028",
     "Shippable, signed, supported release",
     "Supply-chain compromise; unsigned artifacts",
     "Signed + notarized; SBOM published; pen test clean; IR runbooks ready"),
]


def render_roadmap() -> str:
    out = [GEN_NOTE, "# Implementation Roadmap\n\n",
           "Phased technical roadmap. Each phase defines inputs, outputs, "
           "dependencies, deliverables, risks, and exit criteria. This is a "
           "documentation/planning artifact; **no application code is part of "
           "this repository**.\n\n"]
    out.append(mermaid(
        "flowchart TB\n" + "\n".join(
            f"  P{i}[{p[0]}]" for i, p in enumerate(PHASES)) + "\n" +
        "\n".join(f"  P{i} --> P{i+1}" for i in range(len(PHASES) - 1))))
    out.append("\n")
    for i, (name, inp, outp, deps, deliv, risks, exitc) in enumerate(PHASES, 1):
        out.append(f"## Phase {i}: {name}\n\n"
                   f"- **Inputs:** {inp}\n"
                   f"- **Outputs:** {outp}\n"
                   f"- **Dependencies:** {deps}\n"
                   f"- **Deliverables:** {deliv}\n"
                   f"- **Risks:** {risks}\n"
                   f"- **Exit Criteria:** {exitc}\n\n")
    out.append("> Navigation: [Architecture Index](./README.md)\n")
    return "".join(out)


# --- main ------------------------------------------------------------------

def main() -> None:
    derive_relationships()

    # top-level
    write(DOCS / "README.md", render_docs_home())

    # architecture indexes + planning
    write(DOCS / "architecture" / "README.md", render_architecture_index())
    write(DOCS / "architecture" / "component-index.md", render_component_index())
    write(DOCS / "architecture" / "security-index.md", render_security_index())
    write(DOCS / "architecture" / "threat-index.md", render_threat_index())
    write(DOCS / "architecture" / "storage-index.md", render_storage_index())
    write(DOCS / "architecture" / "dependency-graph.md", render_dependency_graph())
    write(DOCS / "architecture" / "ARCHITECTURE-REVIEW.md", render_review())
    write(DOCS / "architecture" / "implementation-roadmap.md", render_roadmap())

    # rfc index
    write(DOCS / "rfcs" / "README.md", render_rfc_index())

    # per-RFC
    for rid in all_rfc_ids():
        r = REGISTRY[rid]
        base = DOCS / "rfcs" / rid
        (base / "diagrams").mkdir(parents=True, exist_ok=True)
        (base / "images").mkdir(parents=True, exist_ok=True)
        write(base / "references.md", render_references(rid))
        write(base / "glossary.md", render_glossary(rid))
        (base / "images" / ".gitkeep").write_text("", encoding="utf-8")
        if r["existing"]:
            write(base / "README.md", render_existing_readme(rid))
        else:
            write(base / "README.md", render_new_readme(rid))
            write(base / "part-01.md", render_new_proposal_body(rid))
            for d in r["diagrams"]:
                write(base / "diagrams" / f"{d['name']}.md",
                      render_rfc_diagram_file(rid, d))
        # keep diagrams dir non-empty for existing RFCs too
        if not r["diagrams"]:
            (base / "diagrams" / ".gitkeep").write_text("", encoding="utf-8")

    # cross-cutting diagrams
    write(DOCS / "diagrams" / "README.md", render_diagram_index())
    for name, title, code in CROSS_DIAGRAMS:
        write(DOCS / "diagrams" / f"{name}.md",
              render_cross_diagram(name, title, code))

    # adr + decisions
    write(DOCS / "decisions" / "README.md", render_decision_index())
    for i, (t, d) in enumerate(ADRS, 1):
        write(DOCS / "adr" / f"ADR-{i:04d}.md", render_adr(i, t, d))
    write(DOCS / "adr" / "README.md",
          GEN_NOTE + "# Architecture Decision Records\n\n"
          "See the [Decision Index](../decisions/README.md) for the full list. "
          "ADRs 0001–0020 are the ratified Security Architecture Decisions "
          "from [RFC-0002 Part 9](../rfcs/RFC-0002/part-09.md).\n")

    # glossary
    write(DOCS / "glossary" / "README.md", render_glossary_master())

    # templates
    tpl_index = [GEN_NOTE, "# Templates\n\nReusable templates for consistent "
                 "authoring. Copy and fill in.\n\n"]
    for fn in sorted(TEMPLATES):
        tpl_index.append(f"- [{fn}](./{fn})\n")
        write(DOCS / "templates" / fn, TEMPLATES[fn])
    write(DOCS / "templates" / "README.md", "".join(tpl_index))

    # simple directory READMEs
    for d, (title, body) in DIR_READMES.items():
        write(DOCS / d / "README.md", GEN_NOTE + f"# {title}\n\n" + body +
              "\n> Navigation: [Architecture Index](../architecture/README.md)\n")

    print("Documentation generation complete.")


if __name__ == "__main__":
    main()
